# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DZ12-TableView' do
  pod 'KeychainSwift', '~> 19.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DZ12-TableView

end
